### ISSUE TITLE
Access Violation fail npm install on Linux

### ISSUE THREAD

**Issue by logannc** [dalekjs/dalek-browser-chrome#21]
I'm running Linux Mint and when I run `sudo npm install dalek-browser-chrome --save-dev`, it fails with the error: 

    Chromedriver installation failed Error: EACCES, permission denied '/home/logan/tmp/chromedriver'
        at Object.fs.mkdirSync (fs.js:647:18)
        at mkdir (/home/logan/node_modules/dalek-browser-chrome/install.js:156:8)
        at Promise._successFn (/home/logan/node_modules/dalek-browser-chrome/install.js:177:7)
        at nextTickCallback (/home/logan/node_modules/dalek-browser-chrome/node_modules/kew/kew.js:47:28)
        at process._tickCallback (node.js:415:13)
    npm WARN This failure might be due to the use of legacy binary "node"
    npm WARN For further explanations, please read /usr/share/doc/nodejs/README.Debian

I have tried with the default version (0.0.11) all the way down to 0.0.7 since that was the version working on the previous installation failure issue. I am led to believe this is an issue in the installation script due to  http://stackoverflow.com/questions/18427497/error-installing-dalek-js-module-chrome-browser. 

If there is anything I can do to fix the environment it is running in or install from the repo, I'm willing to do that. I'd just like to get it working, ya know?

**Comment by asciidisco** [comment]
I think the `sudo` part is the problem, you shouldn't need to do this: See https://gist.github.com/isaacs/579814

**Comment by logannc** [comment]
I keep forgetting to test this on my work computer. I will hopefully test in the morning.
